### ISSUE TITLE
adminui / ngadminui preview is broken

### ISSUE THREAD

**Issue by fwoldt** [netgen/media-site-legacy#2]
create a new media-site-legacy projcect
go to  /ngadminui
and than preivew 

![image](https://user-images.githubusercontent.com/417608/220984136-9a5d82b7-4f37-49cc-97d5-2834c98eba55.png)

**Comment by fwoldt** [comment]
the problem exist in  adminui, too

![image](https://user-images.githubusercontent.com/417608/221115078-940350ac-caad-4a00-8a30-bc92e0ef3715.png)

**Comment by fwoldt** [comment]
in the old setup their was an ezplatform.yml which defines a pagelayout_legacy.yml
https://github.com/netgen/media-site-legacy/blob/ca4e1eb1260e0131ae90b6be6e90d6aa8183b1ba/src/AppBundle/Resources/config/ezplatform.yml
![image](https://user-images.githubusercontent.com/417608/221131634-ccc7bc69-9389-49e2-b2cf-be672088cb13.png)
i think something like this is needed

**Comment by emodric** [comment]
Fixed with https://github.com/netgen/ibexa-legacy-bridge/commit/c3099a3ba33cb78d30082afd38404727f044a90a
