### ISSUE TITLE
Swapped content class group ids in legacy injected_settings

### ISSUE THREAD

**Issue by benkmugo** [netgen/media-site-legacy#3]
Hi @emodric 

I was debugging some odd behaviour for the "Create new" menu in the admin interface, where the menu was showing options belonging to the wrong group e.g. showed media items while in the user groups subtree

It came down to the legacy settings having swapped ids from the "default".
The default ids for the Media and Users for legacy installs I can see across our projects is: Users (2), Media (3)

Once I switched these two the issue was resolved.
https://github.com/netgen/media-site-legacy/blob/82b0e5c222df20e84d148a345d17cace987a70de/config/app/packages/legacy.yaml#L54
https://github.com/netgen/media-site-legacy/blob/82b0e5c222df20e84d148a345d17cace987a70de/config/app/packages/legacy.yaml#L55

Could those setting be updated, or was there a reason for the swap?

Thanks,
Ben

**Comment by emodric** [comment]
Hi, yes, this is because in our demo data, IDs are swapped, who knows why any more 😂

**Comment by benkmugo** [comment]
😂 good times.
Maybe adding a comment just above that setting to make sure people check _their_ actual IDs would be enough?

**Comment by emodric** [comment]
Sure. Mind creating a PR?

**Comment by benkmugo** [comment]
PR #4 is up now. Feel free to amend wording as you see fit.

Thanks again for providing the package and taking this on board.

**Comment by emodric** [comment]
Thanks Benjamin, merged the PR!
